Repository EFUB-EPRIS/EPRIS-Front, pull requests merged in 2024-09, with the labels that each got.

#60 EPRians, Join us 페이지에 디자인 QA를 반영한다.
  src/components/EPRians-admin/TableRow.jsx
  src/components/EPRians/Dropdown.jsx
  src/components/EPRians/ViewMoreButton.jsx
  src/components/EPRians/ViewMoreButton.style.js
  src/components/common/CommonButtons/CommonButtons.jsx
  src/pages/Admin/Eprians/EPRiansPage.jsx
  src/pages/Admin/Recruitment/RecruitmentPage.jsx
  src/pages/EPRians/EPRiansPage.jsx
  src/pages/EPRians/EPRiansPage.style.js
  src/pages/Joinus/JoinusPage.jsx
  src/pages/Joinus/JoinusPage.style.js
Labels: 🔧 fix, 🧚ui

#58 Main과 ClassInfo 뒷페이지에 디자인 QA 요구사항을 반영한다.
  src/components/ClassInfo-admin/CardComponent.jsx
  src/components/Main/Greetings.style.js
  src/pages/Main/MainPage.jsx
  src/pages/Main/MainPage.style.js
Labels: 🔧 fix, 🧚ui

#59 애니메이션 속도, activities 페이지, admin-activities 페이지에 디자인 QA를 반영한다.
  src/api/project.js
  src/components/activities-admin/AwardStatistics.jsx
  src/components/activities-admin/CorporateProject.jsx
  src/components/activities-admin/ProjectItem.jsx
  src/components/activities-admin/ProjectList.jsx
  src/components/activities-admin/UploadItem.jsx
  src/components/activities/Carousel.jsx
  src/components/activities/Carousel.style.js
  src/components/activities/CorporateCard.jsx
  src/components/activities/CorporateCard.style.js
  src/components/common/NavigationBar/NavigatonBar.jsx
  src/components/common/NavigationBar/NavigatonBar.style.js
  src/hooks/useHorizontalScroll.js
  src/hooks/useScrollFadeIn.js
  src/pages/About/AboutPage.jsx
  src/pages/About/AboutPage.style.js
  src/pages/Activity/ActivityPage.jsx
  src/pages/Activity/ActivityPage.style.js
Labels: 🔧 fix, 🧚ui

#61 디자인 QA 반영한 2차 배포를 위해 점검한다.
  src/components/activities/Carousel.jsx
  src/components/common/NavigationBar/NavigatonBar.style.js
  src/pages/Contact/ContactPage.jsx
  src/pages/EPRians/EPRiansPage.jsx
  src/pages/Joinus/JoinusPage.jsx
Labels: 🔧 fix, 💚chore

#62 스크롤 오류를 수정한다.
  src/components/activities/Carousel.jsx
Labels: 🔧 fix

#67 admin corporate-logo 부분 사진 비율 삭제를 한다.
  src/components/activities-admin/CorporateProject.jsx
  src/components/activities/Carousel.style.js
  src/pages/Admin/Eprians/EPRiansPage.jsx
  src/styles/global.css
Labels: 🧚ui

#69 About 페이지 로고 우측 최소 여백을 추가한다.
  src/pages/About/AboutPage.style.js
Labels: 🔧 fix, 🧚ui

#70 캐러셀 코드 개선을 한다.
  src/components/activities/Carousel.jsx
  src/components/activities/Carousel.style.js
  src/components/activities/CorporateCard.jsx
  src/components/activities/CorporateCard.style.js
  src/hooks/useHorizontalScroll.js
Labels: 🍏 refactor

#73 미팅에서의 수정 요구사항을 수정한다.
  public/index.html
  src/components/common/Footer/Footer.jsx
  src/pages/About/AboutPage.jsx
  src/pages/Main/MainPage.jsx
  src/pages/Main/MainPage.style.js
Labels: 🔧 fix

#74 about, eprians, activities, contact 제목 부분에 애니메이션을 추가한다.
  src/hooks/useScrollFadeIn.js
  src/pages/About/AboutPage.jsx
  src/pages/Activity/ActivityPage.jsx
  src/pages/Contact/ContactPage.jsx
  src/pages/EPRians/EPRiansPage.jsx
  src/pages/EPRians/EPRiansPage.style.js
Labels: 🧚ui

#75 Joinus 페이지 모바일 버전 디자인을 수정한다.
  src/components/Joinus/ProcessBox.style.js
  src/pages/Joinus/JoinusPage.jsx
  src/pages/Joinus/JoinusPage.style.js
Labels: 🧚ui

#76 시연 후 수정사항을 배포에 반영한다.
  public/index.html
  src/components/Joinus/ProcessBox.style.js
  src/components/common/Footer/Footer.jsx
  src/hooks/useScrollFadeIn.js
  src/pages/About/AboutPage.jsx
  src/pages/Activity/ActivityPage.jsx
  src/pages/Contact/ContactPage.jsx
  src/pages/EPRians/EPRiansPage.jsx
  src/pages/EPRians/EPRiansPage.style.js
  src/pages/Joinus/JoinusPage.jsx
  src/pages/Joinus/JoinusPage.style.js
  src/pages/Main/MainPage.jsx
  src/pages/Main/MainPage.style.js
Labels: 🔧 fix, 🧚ui
