Repository EFUB-EPRIS/EPRIS-Front, pull requests merged in 2024-08, with the labels that each got.

#6 [FE] 푸터 퍼블리싱을 한다.
  package-lock.json
  package.json
  src/assets/Footer/blog.svg
  src/assets/Footer/instagram.svg
  src/assets/Footer/logo_circle.svg
  src/assets/Footer/mail.svg
  src/components/common/Footer.jsx
  src/components/common/Footer.style.js
Labels: 🧚ui

#2 사진 업로드 컴포넌트와 공통 버튼 퍼블리싱을 한다.
  package-lock.json
  src/assets/arrow_right.svg
  src/assets/plus.svg
  src/assets/xbox.svg
  src/components/common/CommonButtons/CommonButtons.jsx
  src/components/common/CommonButtons/CommonButtons.style.js
  src/components/common/UploadComponent/UploadComponent.jsx
  src/components/common/UploadComponent/UploadComponent.style.js
Labels: 🧚ui

#8 라우팅 기본 설정을 한다.
  src/App.js
  src/components/common/CommonButtons/CommonButtons.style.js
  src/components/common/NavigatonBar.jsx
  src/index.js
  src/pages/About/AboutPage.jsx
  src/pages/Activity/ActivityPage.jsx
  src/pages/Admin/ActivityPage.jsx
  src/pages/Admin/ClassInfoPage.jsx
  src/pages/Admin/EPRiansPage.jsx
  src/pages/Admin/LoginPage.jsx
  src/pages/Admin/RecruitmentPage.jsx
  src/pages/Contact/ContactPage.jsx
  src/pages/EPRians/EPRiansPage.jsx
  src/pages/Joinus/JoinusPage.jsx
  src/pages/LayoutPage.jsx
  src/pages/Main/MainPage.jsx
  src/styles/font.js
  src/styles/global.css
Labels: 💚chore

#11 admin 페이지 INB를 만들고 네비바 컴포넌트를 수정한다.
  src/App.js
  src/assets/arrow_right.svg
  src/components/common/CommonButtons/CommonButtons.jsx
  src/components/common/CommonButtons/CommonButtons.style.js
  src/components/common/Example.jsx
  src/components/common/Example.style.js
  src/components/common/InbAdmin.jsx
  src/components/common/InbAdmin.style.js
  src/components/common/NavigatonBar.jsx
  src/components/common/NavigatonBar.style.js
  src/hooks/useResizeTextarea.js
Labels: 🔧 fix, 🧚ui

#13 EPRians 페이지, Joinus 페이지, Admin_EPRians, Admin_Recruitment 페이지 퍼블리싱을 한다.
  src/assets/Admin_EPRiansPage/ms.svg
  src/assets/Admin_EPRiansPage/ps-mini.svg
  src/assets/Admin_EPRiansPage/ps-row.svg
  src/assets/Admin_EPRiansPage/ps.svg
  src/assets/Admin_EPRiansPage/toggle-off.svg
  src/assets/Admin_EPRiansPage/toggle-on.svg
  src/assets/EPRiansPage/arrow_downward.svg
  src/assets/EPRiansPage/arrow_upward.svg
  src/assets/EPRiansPage/background_img.svg
  src/assets/EPRiansPage/brand_example.svg
  src/assets/EPRiansPage/chevron-down.svg
  src/assets/EPRiansPage/profile_basic.png
  src/assets/JoinusPage/download.svg
  src/assets/JoinusPage/poster_img.png
  src/assets/commonComponents/plus.svg
  src/assets/commonComponents/xbox.svg
  src/components/Admin_EPRiansPage/CustomCheckbox.jsx
  src/components/Admin_EPRiansPage/CustomCheckbox.style.js
  src/components/Admin_EPRiansPage/MemberTable.jsx
  src/components/Admin_EPRiansPage/MemberTable.style.js
  src/components/EPRiansPage/Card.jsx
  src/components/EPRiansPage/Card.style.js
  src/components/EPRiansPage/Dropdown.jsx
  src/components/EPRiansPage/Dropdown.style.js
  src/components/EPRiansPage/ViewMoreButton.jsx
  src/components/EPRiansPage/ViewMoreButton.style.js
  src/components/JoinusPage/ProcessBox.jsx
  src/components/JoinusPage/ProcessBox.style.js
  src/components/JoinusPage/Question.jsx
  src/components/JoinusPage/Question.style.js
  src/components/common/CommonButtons/CommonButtons.jsx
  src/components/common/CommonButtons/CommonButtons.style.js
  src/components/common/UploadComponent/UploadComponent.jsx
  src/components/common/UploadComponent/UploadComponent.style.js
  src/pages/Admin/EPRiansPage.jsx
  src/pages/Admin/EPRiansPage.style.js
  src/pages/Admin/RecruitmentPage.jsx
  src/pages/Admin/RecruitmentPage.style.js
  src/pages/EPRians/EPRiansPage.jsx
  src/pages/EPRians/EPRiansPage.style.js
  src/pages/Joinus/JoinusPage.jsx
  src/pages/Joinus/JoinusPage.style.js
Labels: 🧚ui

#24 axios 인스턴스를 생성한다.
  package-lock.json
  package.json
  src/api/example.js
  src/api/index.js
Labels: 💚chore

#26 Presigned Url로 이미지 업로드 컴포넌트를 만든다.
  src/api/fileUpload.js
  src/api/logo.js
  src/api/member.js
  src/api/recruitment.js
  src/components/common/UploadComponent/UploadComponent.jsx
  src/pages/Admin/EPRiansPage.jsx
Labels: ✨feature

#16 About & Contact 페이지와 admin_login, admin_classinfo 페이지를 퍼블리싱한다
  src/assets/AboutPage/about_background_img.svg
  src/assets/AboutPage/left.svg
  src/assets/AboutPage/right.svg
  src/assets/ContactPage/Ellipse31.svg
  src/assets/ContactPage/Ellipse32.svg
  src/assets/ContactPage/Group 21.svg
  src/assets/ContactPage/blog.svg
  src/assets/ContactPage/instagram.svg
  src/assets/ContactPage/mail.svg
  src/assets/ContactPage/phone.svg
  src/components/About/CardContent.jsx
  src/pages/About/AboutPage.jsx
  src/pages/About/AboutPage.style.js
  src/pages/Admin/ClassInfoPage.jsx
  src/pages/Admin/ClassInfoPage.style.js
  src/pages/Admin/LoginPage.jsx
  src/pages/Admin/LoginPage.style.js
  src/pages/Contact/ContactPage.jsx
  src/pages/Contact/ContactPage.style.js
  src/pages/LayoutPage.jsx
Labels: 🧚ui

#43 Main, admin_class info 페이지에 api를 연결한다.
  src/api/admin.js
  src/api/fileUpload.js
  src/api/main.js
  src/components/Admin/CardComponent.jsx
  src/components/Main/Greetings.jsx
  src/components/Main/Greetings.style.js
  src/components/common/Footer.jsx
  src/components/common/Footer.style.js
  src/components/common/UploadComponent/UploadComponent.jsx
  src/pages/Admin/ClassInfo2Page.jsx
  src/pages/Admin/ClassInfo2Page.style.js
  src/pages/Main/MainPage.jsx
Labels: ✨feature

#36 activities 페이지, admin-activities 페이지에 api 연결을 한다.
  src/App.js
  src/api/award.js
  src/api/corporate.js
  src/api/index.js
  src/api/login.js
  src/api/network.js
  src/api/project.js
  src/api/session.js
  src/components/activities-admin/AdminActivityItem.style.js
  src/components/activities-admin/AwardStatistics.jsx
  src/components/activities-admin/CorporateProject.jsx
  src/components/activities-admin/Network.jsx
  src/components/activities-admin/ProjectItem.jsx
  src/components/activities-admin/ProjectList.jsx
  src/components/activities-admin/SessionList.jsx
  src/components/activities-admin/UploadItem.jsx
  src/components/activities/ActivityCard.jsx
  src/components/activities/CorporateCard.jsx
  src/components/common/NavigatonBar.jsx
  src/components/common/UploadComponent/UploadComponent.jsx
  src/hooks/useResizeTextarea.js
  src/hooks/useScrollFadeIn.js
  src/pages/Activity/ActivityPage.jsx
  src/pages/Admin/ActivityPage.jsx
  src/pages/Admin/LoginPage.jsx
  src/pages/PrivateRouter.jsx
  src/styles/global.css
Labels: ✨feature

#42 Contact, admin_class info 페이지에 api를 연결한다.
  src/api/classinfo.js
  src/components/About/CardContent.jsx
  src/components/About/DepartmentCard.jsx
  src/components/common/NavigatonBar.style.js
  src/pages/About/AboutPage.jsx
  src/pages/About/AboutPage.style.js
  src/pages/Admin/ClassInfoPage.jsx
  src/pages/Contact/ContactPage.jsx
  src/pages/Contact/ContactPage.style.js
Labels: ✨feature

#46 Main, Class_info 뒷페이지에 대한 에러 사항을 수정한다.
  src/api/admin.js
  src/api/main.js
  src/assets/Main/background_img.webp
  src/assets/Main/m_background_img.webp
  src/components/Admin_RecruitmentPage/FileUploadComponent.jsx
  src/components/Admin_RecruitmentPage/FileUploadComponent.style.js
  src/components/ClassInfo-admin/CardComponent.jsx
  src/components/Main/Greetings.jsx
  src/components/Main/Greetings.style.js
  src/components/common/Footer/Footer.jsx
  src/pages/Admin/ClassInfo/ClassInfo2Page.jsx
  src/pages/Main/MainPage.jsx
  src/pages/Main/MainPage.style.js
  src/pages/PrivateRouter.jsx
Labels: 🔧 fix

#45 About, Contact, Class_info 페이지 에러를 수정을 한다.
  src/App.js
  src/components/About/CardContent.jsx
  src/components/common/NavigationBar/NavigatonBar.style.js
  src/pages/About/AboutPage.jsx
  src/pages/About/AboutPage.style.js
  src/pages/Activity/ActivityPage.jsx
  src/pages/Admin/Activity/ActivityPage.jsx
  src/pages/Admin/ClassInfo/ClassInfoMainPage.jsx
  src/pages/Admin/ClassInfo/ClassInfoPage.jsx
  src/pages/Contact/ContactPage.jsx
  src/pages/Contact/ContactPage.style.js
Labels: 🔧 fix

#48 EPRians, Join us 페이지 오류를 수정한다.
  src/assets/arrow_right.svg
  src/components/EPRians-admin/MemberTable.jsx
  src/components/EPRians-admin/MemberTable.style.js
  src/components/EPRians-admin/TableRow.jsx
  src/components/EPRians/Card.jsx
  src/components/EPRians/Dropdown.jsx
  src/components/EPRians/ViewMoreButton.jsx
  src/components/common/CommonButtons/CommonButtons.jsx
  src/components/common/CommonButtons/CommonButtons.style.js
  src/components/common/UploadComponent/UploadComponent.jsx
  src/pages/Admin/Eprians/EPRiansPage.jsx
  src/pages/EPRians/EPRiansPage.jsx
  src/pages/EPRians/EPRiansPage.style.js
  src/pages/Joinus/JoinusPage.jsx
Labels: 🔧 fix

#47 activities 페이지 에러 수정을 한다.
  src/api/index.js
  src/components/Activities-admin/AwardStatistics.jsx
  src/components/Activities-admin/CorporateProject.jsx
  src/components/Activities-admin/Network.jsx
  src/components/Activities-admin/ProjectItem.jsx
  src/components/Activities-admin/ProjectList.jsx
  src/components/Activities-admin/SessionList.jsx
  src/components/Activities-admin/UploadItem.jsx
  src/components/activities/AchievementCard.style.js
  src/components/activities/ActivityCard.jsx
  src/components/activities/ActivityCard.style.js
  src/components/activities/Carousel.jsx
  src/components/activities/Carousel.style.js
  src/components/activities/CorporateCard.jsx
  src/components/activities/CorporateCard.style.js
  src/components/activities/FloatingButton.jsx
  src/components/activities/FloatingButton.style.js
  src/components/activities/ProjectCard.jsx
  src/pages/Activity/ActivityPage.jsx
  src/pages/Activity/ActivityPage.style.js
  src/pages/Admin/Login/LoginPage.jsx
Labels: 🔧 fix

#52 UI 에러를 수정한다.
  src/pages/Main/MainPage.style.js
Labels: 🔧 fix, 🧚ui

#54 내비게이션바의 배경 색을 수정한다.
  src/components/common/NavigationBar/NavigatonBar.jsx
  src/components/common/NavigationBar/NavigatonBar.style.js
Labels: 🔧 fix, 🧚ui

#49 콘솔 에러 및 파일을 정리한다.
  src/assets/activity/right.svg
  src/components/About/DepartmentCard.jsx
  src/components/Recruitment-admin/FileUploadComponent.jsx
  src/components/Recruitment-admin/FileUploadComponent.style.js
  src/components/activities/ActivityCard.jsx
  src/components/activities/CorporateCard.style.js
  src/components/common/NavigationBar/NavigatonBar.jsx
  src/pages/About/AboutPage.style.js
  src/pages/Admin/ClassInfo/ClassInfoPage.jsx
  src/pages/Admin/Recruitment/RecruitmentPage.jsx
  src/pages/PrivateRouter.jsx
Labels: 💚chore

#57 About, Class_info 페이지의 에러 사항을 수정한다
  src/assets/AboutPage/left.svg
  src/pages/About/AboutPage.style.js
  src/pages/Admin/ClassInfo/ClassInfoMainPage.jsx
  src/pages/Admin/ClassInfo/ClassInfoPage.jsx
Labels: 🔧 fix, 🧚ui
